default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: fight_together_development

staging:
  <<: *default
  database: fight_together_staging

production:
  <<: *default
  database: fight_together_production
